###Matrix Programs:

    Python program to add two Matrices
    Python program to multiply two matrices
    Python program for Matrix Product
    Adding and Subtracting Matrices in Python
    Transpose a matrix in Single line in Python
    Python | Matrix creation of n*n
    Python | Get Kth Column of Matrix
    Python – Vertical Concatenation in Matrix


In [11]:
# Program to add two matrices using nested loop
import numpy as np 
X = [[1,2,3], [4 ,5,6],[7,8,9]]
Y = [[9,8,7], [6,5,4], [3,2,1]]
A = np.array(X)
B = np.array(Y)
if A.ndim == B.ndim:
    C= A+B
    print(C)
else:
    print("dim did not match")


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [13]:
#Python program to multiply two matrices
import numpy as np 
X = [[1,2,3], [4 ,5,6],[7,8,9]]
Y = [[9,8,7], [6,5,4], [3,2,1]]
A = np.array(X)
B = np.array(Y)
if A.ndim == B.ndim:
    C= A*B
    print(C)
else:
    print("dim did not match")

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [17]:
#Python program for Matrix Product - elements
# initializing list
p = 1
test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
for ele in test_list:
    for e in ele:
        p = p * e
print(p)

1622880


In [20]:
#Adding and Subtracting Matrices in Python
# creating first matrix
A = np.array([[1, 2], [3, 4]])
  
# creating second matrix
B = np.array([[4, 5], [6, 7]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

print(A-B)

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]


In [31]:
#Transpose a matrix in Single line in Python
import numpy as np
matrix=[[1,2,3],[4,5,6]]
A=np.array(matrix)
print(matrix)
print("\n")
print(np.transpose(matrix))
print("\n")
print(A.T)

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


[[1 4]
 [2 5]
 [3 6]]


In [1]:
##Transpose a matrix in Single line in Python
matrix=[[1,2,3],[4,5,6]]
print(matrix)

new_matrix=zip(*matrix)
for row in new_matrix:
    print(row)

[[1, 2, 3], [4, 5, 6]]
(1, 4)
(2, 5)
(3, 6)


In [4]:
#
# initializing N
N = 3
  
# printing dimension
print("The dimension : " + str(N))
  
# using list comprehension
# matrix creation of n * n
res = [list(range(1 + N * i, 1 + N * (i + 1)))
                            for i in range(N)]
  
# print result
print("The created matrix of N * N: " + str(res))

The dimension : 3
The created matrix of N * N: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [15]:
#
# Get Kth Column of Matrix
# using list comprehension
  
# initialize list
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
  
# printing original list
print("The original list is : " + str(test_list))
  
# initialize K
K = 0
  
# Get Kth Column of Matrix
# using list comprehension
res = [sub[K] for sub in test_list]
print(res)
#method 2
p = list(zip(*test_list))[K]
print(p)

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
[4, 8, 7]
(4, 8, 7)


In [16]:
# Vertical Concatenation in Matrix
# Using join() + list comprehension + zip_longest()
from itertools import zip_longest
  
# initializing lists
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
  
# printing original list
print("The original list : " + str(test_list))
  
# using join to concaternate, zip_longest filling values using 
# "fill"
res = ["".join(ele) for ele in zip_longest(*test_list, fillvalue ="")]
  
# printing result 
print("List after column Concatenation : " + str(res))


The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']
